# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    user_manager:
                class:  TODOBundle\Services\UserManager
                arguments: ["@doctrine.orm.entity_manager", "@other_services"]

    task_manager:
                class: TODOBundle\Services\TaskManager
                arguments: ["@doctrine.orm.entity_manager", "@other_services"]

    other_services:
               class: TODOBundle\Services\OtherServices
               arguments: ["@validator"]
